### ISSUE TITLE
Method setSetting does not exist.

### ISSUE THREAD

**Issue by ghost** [webfox/silverstripe-dropzone-sortable#3]
Can't see that method setSetting exist in Object. So module throws error with SS 3.2.1

Maybe something like this would do?

```
public function setSortableColumn($name) {
     if(!$this->getSetting('sort-column')) {
        $this->settings['sort-column'] = $name;
    }
    return $this->owner;
}
```

**Comment by hailwood** [comment]
Hey @hpeide,

Please checkout the note at the top of the readme - This module depends on a fork of silverstripe-dropzone until the pull request get's merged in.

To use the fork add the below repository key, and then require `"silverstripe-dropzone" : "dev-patch1"`

```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/hailwood/silverstripe-dropzone.git"
    }
],
```

**Comment by darjus01** [comment]
Can you give files because are people that not use composer, thx.

**Comment by hailwood** [comment]
Hi @darjus01 I'm assuming you mean the files for the patched version of dropzone. They can be grabbed from github, here's a link to download that branch as a zip https://github.com/hailwood/silverstripe-dropzone/archive/patch-1.zip
